import { jsx as _jsx, jsxs as _jsxs } from "woby/jsx-runtime";
import { Card, CardMedia, CardContent, CardActions } from "../src/Card";
import { Button } from "../src/Button";
const DefaultCard = () => {
    return (_jsxs(Card, { class: "m-2", children: [_jsx(CardMedia, {}), _jsx(CardContent, { children: "Card Content Sample" }), _jsx(CardActions, { children: "Card Actions Sample" })] }));
};
const VariantCardExample = () => {
    return (_jsx(Card, { cls: "max-w-sm m-2" // sizing & external spacing
        , variant: "elevated" // "elevated" | "outlined" | "filled"
        , elevation: 2, interactive: true, children: _jsxs(CardContent, { children: [_jsx("h3", { class: "text-lg font-semibold", children: "Elevated Card" }), _jsx("p", { class: "text-sm text-gray-600", children: "elevation=2, interactive hover shadow" })] }) }));
};
const OutlinedCardExample = () => (_jsx(Card, { cls: "max-w-sm m-2", variant: "outlined", elevation: 0, children: _jsxs(CardContent, { children: [_jsx("h3", { class: "text-lg font-semibold", children: "Outlined Card" }), _jsx("p", { class: "text-sm text-gray-600", children: "Border only, no elevation" })] }) }));
// style="box-shadow: rgb(255, 6, 6) 0px 2px 1px -1px, rgb(255, 1, 1) 0px 1px 1px 0px, rgb(255, 0, 0) 0px 1px 3px 0px;"
const FilledCardExample = () => (_jsx(Card, { cls: "max-w-sm m-2", variant: "filled", elevation: 0, interactive: true, children: _jsxs(CardContent, { children: [_jsx("h3", { class: "text-lg font-semibold", children: "Filled Card" }), _jsx("p", { class: "text-sm text-gray-600", children: "Subtle filled bg + strong shadow" })] }) }));
const FilledCardExample1 = () => (_jsx(Card, { cls: "max-w-sm m-2", variant: "filled", elevation: 2, interactive: true, children: _jsxs(CardContent, { children: [_jsx("h3", { class: "text-lg font-semibold", children: "Filled Card" }), _jsx("p", { class: "text-sm text-gray-600", children: "Subtle filled bg + strong shadow" })] }) }));
const FilledCardExample2 = () => (_jsx(Card, { cls: "max-w-sm m-2", variant: "filled", elevation: 2, children: _jsxs(CardContent, { children: [_jsx("h3", { class: "text-lg font-semibold", children: "Filled Card" }), _jsx("p", { class: "text-sm text-gray-600", children: "Subtle filled bg + strong shadow" })] }) }));
const FilledCardExample3 = () => (_jsx(Card, { cls: "max-w-sm m-2", variant: "filled", elevation: 3, children: _jsxs(CardContent, { children: [_jsx("h3", { class: "text-lg font-semibold", children: "Filled Card" }), _jsx("p", { class: "text-sm text-gray-600", children: "Subtle filled bg + strong shadow" })] }) }));
const FilledCardExample4 = () => (_jsx(Card, { cls: "max-w-sm m-2", variant: "filled", elevation: 4, children: _jsxs(CardContent, { children: [_jsx("h3", { class: "text-lg font-semibold", children: "Filled Card" }), _jsx("p", { class: "text-sm text-gray-600", children: "Subtle filled bg + strong shadow" })] }) }));
const MediaCenteredCardExample = () => (_jsxs(Card, { cls: "max-w-sm m-2", children: [_jsx(CardMedia, { src: "/sample-avatar.png", alt: "Avatar", cls: "w-24 h-24 rounded-full mx-auto bg-center bg-cover mt-4", position: "center center", fit: "cover" }), _jsxs(CardContent, { cls: "px-5 pb-4", children: [_jsx("h3", { class: "text-lg font-semibold text-center", children: "Taylor" }), _jsx("p", { class: "text-sm text-gray-600 mt-1 text-justify", children: "Front-end engineer focused on fast, accessible components and delightful UX." })] }), _jsx(CardActions, { align: "center", padding: "p-3", children: _jsx(Button, { cls: "px-4 py-2 !rounded-[4px]", onClick: () => alert("Hi Taylor!"), children: "Say Hi" }) })] }));
const ActionsAlignedCardExample = () => (_jsxs(Card, { cls: "max-w-md m-2", children: [_jsxs(CardContent, { padding: "p-6", children: [_jsx("h3", { class: "text-lg font-semibold", children: "Actions Alignment" }), _jsx("p", { class: "text-sm text-gray-600", children: "Try different horizontal justifications" })] }), _jsx(CardActions, { align: "start", padding: "px-4 py-2", children: _jsx("span", { class: "text-xs uppercase text-gray-500", children: "Start" }) }), _jsx(CardActions, { align: "center", padding: "px-4 py-2", children: _jsx("span", { class: "text-xs uppercase text-gray-500", children: "Center" }) }), _jsxs(CardActions, { align: "between", padding: "px-4 py-2", children: [_jsx("span", { class: "text-xs uppercase text-gray-500", children: "Between (left)" }), _jsx("span", { class: "text-xs uppercase text-gray-500", children: "Between (right)" })] }), _jsx(CardActions, { align: "end", padding: "px-4 py-2", children: _jsx("span", { class: "text-xs uppercase text-gray-500", children: "End" }) })] }));
const ContentPaddingCardExample = () => (_jsx(Card, { cls: "max-w-sm m-2", elevation: 1, interactive: true, children: _jsxs(CardContent, { padding: "p-6", children: [_jsx("h3", { class: "text-lg font-semibold", children: "Custom Padding" }), _jsx("p", { class: "text-sm text-gray-600", children: "Using CardContent padding=\"p-6\"" }), _jsx("p", { class: "text-xs text-gray-500 mt-2", children: "Hover to see subtle elevation change." })] }) }));
const NameCardExample = () => (_jsxs(Card, { cls: "max-w-sm m-2", children: [_jsx(CardMedia, { src: "/sample-avatar.png", alt: "Sample avatar", cls: "w-24 h-24 rounded-full mx-auto bg-center bg-cover mt-4", position: "center center", fit: "cover" }), _jsxs(CardContent, { cls: "px-5 pb-4", children: [_jsx("h3", { class: "text-lg font-semibold text-center", children: "Alex" }), _jsx("p", { class: "text-sm text-gray-600 mt-1 text-justify", children: "Product-minded developer who enjoys building cohesive UI systems and great DX." })] }), _jsx(CardActions, { align: "center", padding: "p-3", children: _jsx(Button, { buttonType: "contained", onClick: () => alert("Hello Alex!"), children: "Connect" }) })] }));
const MediaBannerCardExample = () => (_jsxs(Card, { cls: "max-w-md m-2", elevation: 2, children: [_jsx(CardMedia, { src: "contemplative-reptile.jpg", alt: "Banner image", height: "160px", position: "center center", fit: "cover", cls: "w-full" }), _jsxs(CardContent, { children: [_jsx("h3", { class: "text-lg font-semibold", children: "Banner Card" }), _jsx("p", { class: "text-sm text-gray-600", children: "Media header with content below." })] })] }));
const NameCard = () => {
    return (_jsxs(Card, { cls: "max-w-sm m-2 border border-red-500", children: [_jsx(CardMedia, { src: "sample-avatar.png", alt: "Sample avatar", 
                // center the media block and make it round
                cls: "w-24 h-24 rounded-full mx-auto bg-center bg-cover mt-4 border border-yellow-500", height: "96px" // ignored by our custom class height, but harmless
                , 
                // position="center center"
                fit: "cover" }), _jsxs(CardContent, { cls: "px-5 pb-4 mt-2 border border-blue-500", children: [_jsx("h3", { class: "text-lg font-semibold text-center", children: "Ali" }), _jsx("p", { class: "text-sm text-gray-600 mt-1 text-justify", children: "Front-end developer who loves Woby & Tailwind. Passionate about UI micro-interactions and DX." })] }), _jsx(CardActions, { cls: "mt-2 border border-green-500", align: "center", padding: "p-3", children: _jsx(Button, { cls: "p-4 !rounded-[4px]", onClick: () => alert('Hello Ali!'), children: "Say Hi" }) })] }));
};
// export { DefaultCard, VariantCardExample, OutlinedCardExample, FilledCardExample, MediaCenteredCardExample, ActionsAlignedCardExample, ContentPaddingCardExample, NameCardExample, MediaBannerCardExample, NameCard }
export { VariantCardExample, OutlinedCardExample, FilledCardExample, MediaCenteredCardExample, ActionsAlignedCardExample, ContentPaddingCardExample, MediaBannerCardExample };
