import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "woby/jsx-runtime";
import { $ } from 'woby';
import { AlignButton } from '../../src/Editor/AlignButton';
import { EditorContext } from '../../src/Editor/undoredo';
const AlignButtonDemo = () => {
    const editorRef = $(null);
    return _jsx(_Fragment, { children: _jsx(EditorContext.Provider, { value: editorRef, children: _jsxs("div", { class: "mb-4", children: [_jsx("p", { class: "m-2 ", children: "Disabled Button" }), _jsxs("div", { class: "flex gap-4 items-center my-2 border border-gray-300 rounded p-4", children: [_jsx(AlignButton, { mode: "left", disabled: true }), _jsx(AlignButton, { mode: "center", disabled: true }), _jsx(AlignButton, { mode: "right", disabled: true }), _jsx(AlignButton, { mode: "justify", disabled: true })] }), _jsx("p", { class: "m-2 ", children: "Enabled Button" }), _jsxs("div", { class: "flex gap-4 items-center my-2 border border-gray-300 rounded p-4", children: [_jsx(AlignButton, { mode: "left", class: "text-black" }), _jsx(AlignButton, { mode: "center", class: "text-black" }), _jsx(AlignButton, { mode: "right", class: "text-black" }), _jsx(AlignButton, { mode: "justify", class: "text-black" })] }), _jsxs("div", { contentEditable: true, class: "border border-gray-300 rounded p-4 min-h-[200px] mb-4 focus:outline-none focus:ring-2 focus:ring-blue-500", children: [_jsx("p", { children: "Select this text and try the alignment buttons below!" }), _jsx("p", { children: "You can align left, center, right or justify text." }), _jsx("br", {}), _jsx("p", { children: "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos." })] })] }) }) });
};
export { AlignButtonDemo };
