language: node_js

node_js:
  - "11.10.1"

dist: trusty

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm run mock:create

script:
  - npm run test
  - npm run lint