// Auto-generated by vite-plugin-test, do not edit manually

export * as './test/Wheeler.test' from './test/Wheeler.test'
export * as './test/IconButton.test' from './test/IconButton.test'
export * as './test/Collapse.test' from './test/Collapse.test'
export * as './test/Chip.test' from './test/Chip.test'
export * as './test/Checkbox.test' from './test/Checkbox.test'
export * as './test/Card.test' from './test/Card.test'
export * as './test/Button.test' from './test/Button.test'
export * as './test/Badge.test' from './test/Badge.test'
export * as './test/Avatar.test' from './test/Avatar.test'
export * as './test/Appbar.test' from './test/Appbar.test'
export * as './test/AlignButton.test' from './test/AlignButton.test'